import { database } from "@db/connection.db";
import { clientes } from "@model/tables/cliente.model";

export async function seedClientes() {
  console.log("🌱 Seeding clients...");

  const clientsData = await database
    .insert(clientes)
    .values([
      {
        dni: "70123456",
        nombres: "Ana",
        apellidos: "Martinez Lopez",
        nombreCompleto: "Ana Martinez Lopez",
        email: "ana.martinez@gmail.com",
        telefono: "987654321",
        direccion: "Av. Arequipa 1234, Lima",
        imagenes: ["https://iili.io/fubznoB.jpg"],
      },
      {
        dni: "70234567",
        nombres: "Pedro",
        apellidos: "Gonzales Quispe",
        nombreCompleto: "Pedro Gonzales Quispe",
        email: "pedro.gonzales@hotmail.com",
        telefono: "912345678",
        direccion: "Jr. Cusco 567, Arequipa",
        imagenes: ["https://iili.io/fubzuSa.jpg"],
      },
      {
        dni: "70345678",
        nombres: "Lucia",
        apellidos: "Fernandez Castro",
        nombreCompleto: "Lucia Fernandez Castro",
        email: "lucia.fernandez@gmail.com",
        telefono: "945678123",
        direccion: "Calle Lima 890, Trujillo",
        imagenes: ["https://iili.io/fubzRHJ.jpg"],
      },
      {
        dni: "70456789",
        nombres: "Roberto",
        apellidos: "Vargas Mendoza",
        nombreCompleto: "Roberto Vargas Mendoza",
        email: "roberto.vargas@outlook.com",
        telefono: "923456789",
        direccion: "Av. Tacna 321, Chiclayo",
        imagenes: ["https://iili.io/fubz5Av.jpg"],
      },
      {
        dni: "70567890",
        nombres: "Carmen",
        apellidos: "Rojas Huaman",
        nombreCompleto: "Carmen Rojas Huaman",
        email: null,
        telefono: "956789012",
        direccion: "Jr. Puno 456, Puno",
        imagenes: ["https://iili.io/fubz7NR.jpg"],
      },
      {
        dni: "70678901",
        nombres: "Miguel",
        apellidos: "Torres Diaz",
        nombreCompleto: "Miguel Torres Diaz",
        email: "miguel.torres@gmail.com",
        telefono: "978123456",
        direccion: "Av. La Marina 789, Callao",
        imagenes: ["https://iili.io/fubzYtp.jpg"],
      },
      {
        dni: "70789012",
        nombres: "Sofia",
        apellidos: "Ramirez Flores",
        nombreCompleto: "Sofia Ramirez Flores",
        email: "sofia.ramirez@hotmail.com",
        telefono: "934567890",
        direccion: "Jr. Union 234, Huancayo",
        imagenes: ["https://iili.io/fubzlVI.jpg"],
      },
      {
        dni: "70890123",
        nombres: "Jorge",
        apellidos: "Castro Medina",
        nombreCompleto: "Jorge Castro Medina",
        email: "jorge.castro@outlook.com",
        telefono: "967890123",
        direccion: "Calle Real 567, Piura",
        imagenes: ["https://iili.io/fubzGln.jpg"],
      },
      {
        dni: "70901234",
        nombres: "Elena",
        apellidos: "Sanchez Ramos",
        nombreCompleto: "Elena Sanchez Ramos",
        email: "elena.sanchez@gmail.com",
        telefono: "921234567",
        direccion: "Av. Universitaria 890, Lima",
        imagenes: ["https://iili.io/fubzXRf.jpg"],
      },
      {
        dni: "71012345",
        nombres: "Ricardo",
        apellidos: "Morales Cruz",
        nombreCompleto: "Ricardo Morales Cruz",
        email: null,
        telefono: "945678901",
        direccion: "Jr. Comercio 123, Tacna",
        imagenes: ["https://iili.io/fubzjDl.jpg"],
      },
      {
        dni: "71123456",
        nombres: "Patricia",
        apellidos: "Vega Silva",
        nombreCompleto: "Patricia Vega Silva",
        email: "patricia.vega@gmail.com",
        telefono: "989012345",
        direccion: "Av. Bolognesi 456, Arequipa",
        imagenes: ["https://iili.io/fubzNx2.jpg"],
      },
      {
        dni: "71234567",
        nombres: "Fernando",
        apellidos: "Jimenez Paredes",
        nombreCompleto: "Fernando Jimenez Paredes",
        email: "fernando.jimenez@hotmail.com",
        telefono: "956123456",
        direccion: "Calle Grau 789, Cusco",
        imagenes: ["https://iili.io/fubzvf9.jpg"],
      },
      {
        dni: "71345678",
        nombres: "Rosa",
        apellidos: "Nunez Castillo",
        nombreCompleto: "Rosa Nunez Castillo",
        email: "rosa.nunez@outlook.com",
        telefono: "923456780",
        direccion: "Jr. Libertad 234, Iquitos",
        imagenes: ["https://iili.io/fubzgHb.jpg"],
      },
      {
        dni: "71456789",
        nombres: "Alberto",
        apellidos: "Herrera Campos",
        nombreCompleto: "Alberto Herrera Campos",
        email: "alberto.herrera@gmail.com",
        telefono: "912345670",
        direccion: "Av. Ejercito 567, Cajamarca",
        imagenes: ["https://iili.io/fubz4Ox.jpg"],
      },
      {
        dni: "71567890",
        nombres: "Diana",
        apellidos: "Ponce Rojas",
        nombreCompleto: "Diana Ponce Rojas",
        email: null,
        telefono: "978901234",
        direccion: "Calle Ayacucho 890, Pucallpa",
        imagenes: ["https://iili.io/fubz6DQ.jpg"],
      },
      {
        dni: "71678901",
        nombres: "Cesar",
        apellidos: "Salazar Mora",
        nombreCompleto: "Cesar Salazar Mora",
        email: "cesar.salazar@gmail.com",
        telefono: "934567801",
        direccion: "Jr. San Martin 123, Tumbes",
        imagenes: ["https://iili.io/fubzLiP.jpg"],
      },
      {
        dni: "71789012",
        nombres: "Monica",
        apellidos: "Rios Gutierrez",
        nombreCompleto: "Monica Rios Gutierrez",
        email: "monica.rios@hotmail.com",
        telefono: "967890124",
        direccion: "Av. Miraflores 456, Lima",
        imagenes: ["https://iili.io/fubzt0F.jpg"],
      },
      {
        dni: "71890123",
        nombres: "Gabriel",
        apellidos: "Mendez Luna",
        nombreCompleto: "Gabriel Mendez Luna",
        email: "gabriel.mendez@outlook.com",
        telefono: "921234568",
        direccion: "Calle Progreso 789, Chimbote",
        imagenes: ["https://iili.io/fubzmJa.jpg"],
      },
      {
        dni: "71901234",
        nombres: "Valeria",
        apellidos: "Ochoa Suarez",
        nombreCompleto: "Valeria Ochoa Suarez",
        email: "valeria.ochoa@gmail.com",
        telefono: "945678902",
        direccion: "Jr. Independencia 234, Huaraz",
        imagenes: ["https://iili.io/fubzp5J.jpg"],
      },
      {
        dni: "72012345",
        nombres: "Daniel",
        apellidos: "Reyes Paz",
        nombreCompleto: "Daniel Reyes Paz",
        email: null,
        telefono: "989012346",
        direccion: "Av. Industrial 567, Sullana",
        imagenes: ["https://iili.io/fubzyOv.jpg"],
      },
      {
        dni: "72123456",
        nombres: "Adriana",
        apellidos: "Flores Vera",
        nombreCompleto: "Adriana Flores Vera",
        email: "adriana.flores@gmail.com",
        telefono: "956123457",
        direccion: "Calle Victoria 890, Ilo",
        imagenes: ["https://iili.io/fubIJxp.jpg"],
      },
      {
        dni: "72234567",
        nombres: "Javier",
        apellidos: "Acosta Lozano",
        nombreCompleto: "Javier Acosta Lozano",
        email: "javier.acosta@hotmail.com",
        telefono: "923456781",
        direccion: "Jr. Progreso 123, Juliaca",
        imagenes: ["https://iili.io/fubIdWN.jpg"],
      },
      {
        dni: "72345678",
        nombres: "Claudia",
        apellidos: "Miranda Valle",
        nombreCompleto: "Claudia Miranda Valle",
        email: "claudia.miranda@outlook.com",
        telefono: "912345671",
        direccion: "Av. Pacifico 456, Talara",
        imagenes: ["https://iili.io/fubIFft.jpg"],
      },
      {
        dni: "72456789",
        nombres: "Ernesto",
        apellidos: "Campos Arias",
        nombreCompleto: "Ernesto Campos Arias",
        email: "ernesto.campos@gmail.com",
        telefono: "978901235",
        direccion: "Calle Central 789, Ica",
        imagenes: ["https://iili.io/fubIK0X.jpg"],
      },
      {
        dni: "72567890",
        nombres: "Beatriz",
        apellidos: "Leon Santos",
        nombreCompleto: "Beatriz Leon Santos",
        email: null,
        telefono: "934567802",
        direccion: "Jr. America 234, Chincha",
        imagenes: ["https://iili.io/fubIBJs.jpg"],
      },
      {
        dni: "72678901",
        nombres: "Marcos",
        apellidos: "Parra Gamboa",
        nombreCompleto: "Marcos Parra Gamboa",
        email: "marcos.parra@gmail.com",
        telefono: "967890125",
        direccion: "Av. Los Heroes 567, Pisco",
        imagenes: ["https://iili.io/fubInef.jpg"],
      },
      {
        dni: "72789012",
        nombres: "Silvia",
        apellidos: "Ortiz Cabrera",
        nombreCompleto: "Silvia Ortiz Cabrera",
        email: "silvia.ortiz@hotmail.com",
        telefono: "921234569",
        direccion: "Calle Los Olivos 890, Nazca",
        imagenes: ["https://iili.io/fubIzzl.jpg"],
      },
      {
        dni: "72890123",
        nombres: "Hector",
        apellidos: "Velasquez Marin",
        nombreCompleto: "Hector Velasquez Marin",
        email: "hector.velasquez@outlook.com",
        telefono: "945678903",
        direccion: "Jr. Las Palmeras 123, Ayacucho",
        imagenes: ["https://iili.io/fubIAq7.jpg"],
      },
      {
        dni: "72901234",
        nombres: "Gloria",
        apellidos: "Cardenas Torres",
        nombreCompleto: "Gloria Cardenas Torres",
        email: "gloria.cardenas@gmail.com",
        telefono: "989012347",
        direccion: "Av. Los Pinos 456, Huanuco",
        imagenes: ["https://iili.io/fubI5ge.jpg"],
      },
      {
        dni: "73012345",
        nombres: "Andres",
        apellidos: "Romero Davila",
        nombreCompleto: "Andres Romero Davila",
        email: null,
        telefono: "956123458",
        direccion: "Calle Las Flores 789, Tingo Maria",
        imagenes: ["https://iili.io/fubIa5b.jpg"],
      },
    ])
    .returning();

  console.log("✅ Clients inserted");
  return clientsData;
}
