import { database } from "@db/connection.db";
import { conductores } from "@model/tables/conductor.model";
import { getDateString } from "@function/date.function";

export async function seedConductores() {
  console.log("🌱 Seeding drivers...");

  const driversData = await database
    .insert(conductores)
    .values([
      {
        dni: "12345678",
        nombre: "Juan Perez Garcia",
        numeroLicencia: "Q07864165",
        claseLicencia: "A",
        categoriaLicencia: "Uno",
        fechaExpedicion: getDateString(-1460),
        fechaRevalidacion: getDateString(120),
        imagenes: ["https://iili.io/fub7gEl.webp"],
      },
      {
        dni: "87654321",
        nombre: "Maria Gomez Torres",
        numeroLicencia: "Q08912345",
        claseLicencia: "B",
        categoriaLicencia: "Dos",
        fechaExpedicion: getDateString(-1825),
        fechaRevalidacion: getDateString(-10),
        imagenes: ["https://iili.io/fub762S.webp"],
      },
      {
        dni: "11223344",
        nombre: "Carlos Ruiz Sanchez",
        numeroLicencia: "Q09123456",
        claseLicencia: "A",
        categoriaLicencia: "Tres",
        fechaExpedicion: getDateString(-1095),
        fechaRevalidacion: getDateString(365),
        imagenes: ["https://iili.io/fub7spe.webp"],
      },
      {
        dni: "22334455",
        nombre: "Luis Martinez Rojas",
        numeroLicencia: "Q09234567",
        claseLicencia: "B",
        categoriaLicencia: "Uno",
        fechaExpedicion: getDateString(-1200),
        fechaRevalidacion: getDateString(200),
        imagenes: ["https://iili.io/fub7QTu.webp"],
      },
      {
        dni: "33445566",
        nombre: "Rosa Fernandez Silva",
        numeroLicencia: "Q09345678",
        claseLicencia: "A",
        categoriaLicencia: "Dos",
        fechaExpedicion: getDateString(-1500),
        fechaRevalidacion: getDateString(150),
        imagenes: ["https://iili.io/fub7Zhb.webp"],
      },
      {
        dni: "44556677",
        nombre: "Miguel Torres Luna",
        numeroLicencia: "Q09456789",
        claseLicencia: "B",
        categoriaLicencia: "Tres",
        fechaExpedicion: getDateString(-1300),
        fechaRevalidacion: getDateString(100),
        imagenes: ["https://iili.io/fub7tQj.webp"],
      },
      {
        dni: "55667788",
        nombre: "Sandra Vargas Cruz",
        numeroLicencia: "Q09567890",
        claseLicencia: "A",
        categoriaLicencia: "Uno",
        fechaExpedicion: getDateString(-1600),
        fechaRevalidacion: getDateString(180),
        imagenes: ["https://iili.io/fub7p4V.webp"],
      },
      {
        dni: "66778899",
        nombre: "Roberto Castro Diaz",
        numeroLicencia: "Q09678901",
        claseLicencia: "B",
        categoriaLicencia: "Dos",
        fechaExpedicion: getDateString(-1400),
        fechaRevalidacion: getDateString(90),
        imagenes: ["https://iili.io/fubYHYP.webp"],
      },
      {
        dni: "77889900",
        nombre: "Patricia Morales Vega",
        numeroLicencia: "Q09789012",
        claseLicencia: "A",
        categoriaLicencia: "Tres",
        fechaExpedicion: getDateString(-1700),
        fechaRevalidacion: getDateString(250),
        imagenes: ["https://iili.io/fubYJv1.webp"],
      },
      {
        dni: "88990011",
        nombre: "Fernando Ramirez Soto",
        numeroLicencia: "Q09890123",
        claseLicencia: "B",
        categoriaLicencia: "Uno",
        fechaExpedicion: getDateString(-1250),
        fechaRevalidacion: getDateString(160),
        imagenes: ["https://iili.io/fubY3Tg.webp"],
      },
      {
        dni: "99001122",
        nombre: "Carmen Jimenez Flores",
        numeroLicencia: "Q09901234",
        claseLicencia: "A",
        categoriaLicencia: "Dos",
        fechaExpedicion: getDateString(-1550),
        fechaRevalidacion: getDateString(130),
        imagenes: ["https://iili.io/fubYFja.webp"],
      },
      {
        dni: "10112233",
        nombre: "Jorge Herrera Campos",
        numeroLicencia: "Q10012345",
        claseLicencia: "B",
        categoriaLicencia: "Tres",
        fechaExpedicion: getDateString(-1350),
        fechaRevalidacion: getDateString(110),
        imagenes: ["https://iili.io/fubYKZJ.webp"],
      },
      {
        dni: "20223344",
        nombre: "Elena Ponce Rojas",
        numeroLicencia: "Q10123456",
        claseLicencia: "A",
        categoriaLicencia: "Uno",
        fechaExpedicion: getDateString(-1650),
        fechaRevalidacion: getDateString(190),
        imagenes: ["https://iili.io/fubYBGR.webp"],
      },
      {
        dni: "30334455",
        nombre: "Andres Salazar Mora",
        numeroLicencia: "Q10234567",
        claseLicencia: "B",
        categoriaLicencia: "Dos",
        fechaExpedicion: getDateString(-1450),
        fechaRevalidacion: getDateString(140),
        imagenes: ["https://iili.io/fubYC4p.webp"],
      },
      {
        dni: "40445566",
        nombre: "Monica Rios Gutierrez",
        numeroLicencia: "Q10345678",
        claseLicencia: "A",
        categoriaLicencia: "Tres",
        fechaExpedicion: getDateString(-1750),
        fechaRevalidacion: getDateString(220),
        imagenes: ["https://iili.io/fubYxaI.webp"],
      },
      {
        dni: "50556677",
        nombre: "Gabriel Mendez Luna",
        numeroLicencia: "Q10456789",
        claseLicencia: "B",
        categoriaLicencia: "Uno",
        fechaExpedicion: getDateString(-1280),
        fechaRevalidacion: getDateString(170),
        imagenes: ["https://iili.io/fubYIyX.webp"],
      },
      {
        dni: "60667788",
        nombre: "Valeria Ochoa Suarez",
        numeroLicencia: "Q10567890",
        claseLicencia: "A",
        categoriaLicencia: "Dos",
        fechaExpedicion: getDateString(-1580),
        fechaRevalidacion: getDateString(125),
        imagenes: ["https://iili.io/fubYAjs.webp"],
      },
      {
        dni: "70778899",
        nombre: "Daniel Reyes Paz",
        numeroLicencia: "Q10678901",
        claseLicencia: "B",
        categoriaLicencia: "Tres",
        fechaExpedicion: getDateString(-1380),
        fechaRevalidacion: getDateString(95),
        imagenes: ["https://iili.io/fubYYG4.webp"],
      },
      {
        dni: "80889900",
        nombre: "Adriana Flores Vera",
        numeroLicencia: "Q10789012",
        claseLicencia: "A",
        categoriaLicencia: "Uno",
        fechaExpedicion: getDateString(-1680),
        fechaRevalidacion: getDateString(210),
        imagenes: ["https://iili.io/fubYa6l.webp"],
      },
      {
        dni: "90990011",
        nombre: "Javier Acosta Lozano",
        numeroLicencia: "Q10890123",
        claseLicencia: "B",
        categoriaLicencia: "Dos",
        fechaExpedicion: getDateString(-1480),
        fechaRevalidacion: getDateString(155),
        imagenes: ["https://iili.io/fubY0aS.webp"],
      },
      {
        dni: "11100122",
        nombre: "Claudia Miranda Valle",
        numeroLicencia: "Q10901234",
        claseLicencia: "A",
        categoriaLicencia: "Tres",
        fechaExpedicion: getDateString(-1780),
        fechaRevalidacion: getDateString(240),
        imagenes: ["https://iili.io/fubYG99.webp"],
      },
      {
        dni: "22211233",
        nombre: "Ernesto Campos Arias",
        numeroLicencia: "Q11012345",
        claseLicencia: "B",
        categoriaLicencia: "Uno",
        fechaExpedicion: getDateString(-1320),
        fechaRevalidacion: getDateString(185),
        imagenes: ["https://iili.io/fubYMue.webp"],
      },
      {
        dni: "33322344",
        nombre: "Beatriz Leon Santos",
        numeroLicencia: "Q11123456",
        claseLicencia: "A",
        categoriaLicencia: "Dos",
        fechaExpedicion: getDateString(-1620),
        fechaRevalidacion: getDateString(135),
        imagenes: ["https://iili.io/fubYWZb.webp"],
      },
      {
        dni: "44433455",
        nombre: "Marcos Parra Gamboa",
        numeroLicencia: "Q11234567",
        claseLicencia: "B",
        categoriaLicencia: "Tres",
        fechaExpedicion: getDateString(-1420),
        fechaRevalidacion: getDateString(105),
        imagenes: ["https://iili.io/fubYjMx.webp"],
      },
      {
        dni: "55544566",
        nombre: "Silvia Ortiz Cabrera",
        numeroLicencia: "Q11345678",
        claseLicencia: "A",
        categoriaLicencia: "Uno",
        fechaExpedicion: getDateString(-1720),
        fechaRevalidacion: getDateString(230),
        imagenes: ["https://iili.io/fubYw6Q.webp"],
      },
      {
        dni: "66655677",
        nombre: "Hector Velasquez Marin",
        numeroLicencia: "Q11456789",
        claseLicencia: "B",
        categoriaLicencia: "Dos",
        fechaExpedicion: getDateString(-1520),
        fechaRevalidacion: getDateString(145),
        imagenes: ["https://iili.io/fubYOFV.webp"],
      },
      {
        dni: "77766788",
        nombre: "Gloria Cardenas Torres",
        numeroLicencia: "Q11567890",
        claseLicencia: "A",
        categoriaLicencia: "Tres",
        fechaExpedicion: getDateString(-1820),
        fechaRevalidacion: getDateString(260),
        imagenes: ["https://iili.io/fubYecB.webp"],
      },
      {
        dni: "88877899",
        nombre: "Andres Romero Davila",
        numeroLicencia: "Q11678901",
        claseLicencia: "B",
        categoriaLicencia: "Uno",
        fechaExpedicion: getDateString(-1360),
        fechaRevalidacion: getDateString(175),
        imagenes: ["https://iili.io/fubYk8P.webp"],
      },
      {
        dni: "99988900",
        nombre: "Natalia Silva Campos",
        numeroLicencia: "Q11789012",
        claseLicencia: "A",
        categoriaLicencia: "Dos",
        fechaExpedicion: getDateString(-1660),
        fechaRevalidacion: getDateString(195),
        imagenes: ["https://iili.io/fubYSAF.webp"],
      },
      {
        dni: "10099011",
        nombre: "Rodrigo Vega Morales",
        numeroLicencia: "Q11890123",
        claseLicencia: "B",
        categoriaLicencia: "Tres",
        fechaExpedicion: getDateString(-1560),
        fechaRevalidacion: getDateString(165),
        imagenes: ["https://iili.io/fubYSAF.webp"],
      },
    ])
    .returning();

  console.log("✅ Drivers inserted");
  return driversData;
}
