import { database } from "@db/connection.db";
import { conductores } from "@model/tables/conductor.model";

export async function seedConductores() {
  console.log("🌱 Seeding drivers...");

  const driversData = await database
    .insert(conductores)
    .values([
      {
        dni: "12345678",
        nombres: "Juan",
        apellidos: "Perez Garcia",
        nombreCompleto: "Juan Perez Garcia",
        numeroLicencia: "Q07864165",
        claseLicencia: "A",
        categoriaLicencia: "Uno",
        email: "xerickcua@gmail.com",
        fotocheck: ["https://iili.io/fub7gEl.webp"],
      },
      {
        dni: "87654321",
        nombres: "Maria",
        apellidos: "Gomez Torres",
        nombreCompleto: "Maria Gomez Torres",
        numeroLicencia: "Q08912345",
        claseLicencia: "B",
        categoriaLicencia: "Dos",
        fotocheck: ["https://iili.io/fub762S.webp"],
      },
      {
        dni: "11223344",
        nombres: "Carlos",
        apellidos: "Ruiz Sanchez",
        nombreCompleto: "Carlos Ruiz Sanchez",
        numeroLicencia: "Q09123456",
        claseLicencia: "A",
        categoriaLicencia: "Tres",
        email: "erixcel.evolution.api@gmail.com",
        fotocheck: ["https://iili.io/fub7spe.webp"],
      },
      {
        dni: "22334455",
        nombres: "Luis",
        apellidos: "Martinez Rojas",
        nombreCompleto: "Luis Martinez Rojas",
        numeroLicencia: "Q09234567",
        claseLicencia: "B",
        categoriaLicencia: "Uno",
        email: "erixcel.gemini.1@gmail.com",
        fotocheck: ["https://iili.io/fub7QTu.webp"],
      },
      {
        dni: "33445566",
        nombres: "Rosa",
        apellidos: "Fernandez Silva",
        nombreCompleto: "Rosa Fernandez Silva",
        numeroLicencia: "Q09345678",
        claseLicencia: "A",
        categoriaLicencia: "Dos",
        fotocheck: ["https://iili.io/fub7Zhb.webp"],
      },
      {
        dni: "44556677",
        nombres: "Miguel",
        apellidos: "Torres Luna",
        nombreCompleto: "Miguel Torres Luna",
        numeroLicencia: "Q09456789",
        claseLicencia: "B",
        categoriaLicencia: "Tres",
        fotocheck: ["https://iili.io/fub7tQj.webp"],
      },
      {
        dni: "55667788",
        nombres: "Sandra",
        apellidos: "Vargas Cruz",
        nombreCompleto: "Sandra Vargas Cruz",
        numeroLicencia: "Q09567890",
        claseLicencia: "A",
        categoriaLicencia: "Uno",
        fotocheck: ["https://iili.io/fub7p4V.webp"],
      },
      {
        dni: "66778899",
        nombres: "Roberto",
        apellidos: "Castro Diaz",
        nombreCompleto: "Roberto Castro Diaz",
        numeroLicencia: "Q09678901",
        claseLicencia: "B",
        categoriaLicencia: "Dos",
        fotocheck: ["https://iili.io/fubYHYP.webp"],
      },
      {
        dni: "77889900",
        nombres: "Patricia",
        apellidos: "Morales Vega",
        nombreCompleto: "Patricia Morales Vega",
        numeroLicencia: "Q09789012",
        claseLicencia: "A",
        categoriaLicencia: "Tres",
        fotocheck: ["https://iili.io/fubYJv1.webp"],
      },
      {
        dni: "88990011",
        nombres: "Fernando",
        apellidos: "Ramirez Soto",
        nombreCompleto: "Fernando Ramirez Soto",
        numeroLicencia: "Q09890123",
        claseLicencia: "B",
        categoriaLicencia: "Uno",
        fotocheck: ["https://iili.io/fubY3Tg.webp"],
      },
      {
        dni: "99001122",
        nombres: "Carmen",
        apellidos: "Jimenez Flores",
        nombreCompleto: "Carmen Jimenez Flores",
        numeroLicencia: "Q09901234",
        claseLicencia: "A",
        categoriaLicencia: "Dos",
        fotocheck: ["https://iili.io/fubYFja.webp"],
      },
      {
        dni: "10112233",
        nombres: "Jorge",
        apellidos: "Herrera Campos",
        nombreCompleto: "Jorge Herrera Campos",
        numeroLicencia: "Q10012345",
        claseLicencia: "B",
        categoriaLicencia: "Tres",
        fotocheck: ["https://iili.io/fubYKZJ.webp"],
      },
      {
        dni: "20223344",
        nombres: "Elena",
        apellidos: "Ponce Rojas",
        nombreCompleto: "Elena Ponce Rojas",
        numeroLicencia: "Q10123456",
        claseLicencia: "A",
        categoriaLicencia: "Uno",
        fotocheck: ["https://iili.io/fubYBGR.webp"],
      },
      {
        dni: "30334455",
        nombres: "Andres",
        apellidos: "Salazar Mora",
        nombreCompleto: "Andres Salazar Mora",
        numeroLicencia: "Q10234567",
        claseLicencia: "B",
        categoriaLicencia: "Dos",
        fotocheck: ["https://iili.io/fubYC4p.webp"],
      },
      {
        dni: "40445566",
        nombres: "Monica",
        apellidos: "Rios Gutierrez",
        nombreCompleto: "Monica Rios Gutierrez",
        numeroLicencia: "Q10345678",
        claseLicencia: "A",
        categoriaLicencia: "Tres",
        fotocheck: ["https://iili.io/fubYxaI.webp"],
      },
      {
        dni: "50556677",
        nombres: "Gabriel",
        apellidos: "Mendez Luna",
        nombreCompleto: "Gabriel Mendez Luna",
        numeroLicencia: "Q10456789",
        claseLicencia: "B",
        categoriaLicencia: "Uno",
        fotocheck: ["https://iili.io/fubYIyX.webp"],
      },
      {
        dni: "60667788",
        nombres: "Valeria",
        apellidos: "Ochoa Suarez",
        nombreCompleto: "Valeria Ochoa Suarez",
        numeroLicencia: "Q10567890",
        claseLicencia: "A",
        categoriaLicencia: "Dos",
        fotocheck: ["https://iili.io/fubYAjs.webp"],
      },
      {
        dni: "70778899",
        nombres: "Daniel",
        apellidos: "Reyes Paz",
        nombreCompleto: "Daniel Reyes Paz",
        numeroLicencia: "Q10678901",
        claseLicencia: "B",
        categoriaLicencia: "Tres",
        fotocheck: ["https://iili.io/fubYYG4.webp"],
      },
      {
        dni: "80889900",
        nombres: "Adriana",
        apellidos: "Flores Vera",
        nombreCompleto: "Adriana Flores Vera",
        numeroLicencia: "Q10789012",
        claseLicencia: "A",
        categoriaLicencia: "Uno",
        fotocheck: ["https://iili.io/fubYa6l.webp"],
      },
      {
        dni: "90990011",
        nombres: "Javier",
        apellidos: "Acosta Lozano",
        nombreCompleto: "Javier Acosta Lozano",
        numeroLicencia: "Q10890123",
        claseLicencia: "B",
        categoriaLicencia: "Dos",
        fotocheck: ["https://iili.io/fubY0aS.webp"],
      },
      {
        dni: "11100122",
        nombres: "Claudia",
        apellidos: "Miranda Valle",
        nombreCompleto: "Claudia Miranda Valle",
        numeroLicencia: "Q10901234",
        claseLicencia: "A",
        categoriaLicencia: "Tres",
        fotocheck: ["https://iili.io/fubYG99.webp"],
      },
      {
        dni: "22211233",
        nombres: "Ernesto",
        apellidos: "Campos Arias",
        nombreCompleto: "Ernesto Campos Arias",
        numeroLicencia: "Q11012345",
        claseLicencia: "B",
        categoriaLicencia: "Uno",
        fotocheck: ["https://iili.io/fubYMue.webp"],
      },
      {
        dni: "33322344",
        nombres: "Beatriz",
        apellidos: "Leon Santos",
        nombreCompleto: "Beatriz Leon Santos",
        numeroLicencia: "Q11123456",
        claseLicencia: "A",
        categoriaLicencia: "Dos",
        fotocheck: ["https://iili.io/fubYWZb.webp"],
      },
      {
        dni: "44433455",
        nombres: "Marcos",
        apellidos: "Parra Gamboa",
        nombreCompleto: "Marcos Parra Gamboa",
        numeroLicencia: "Q11234567",
        claseLicencia: "B",
        categoriaLicencia: "Tres",
        fotocheck: ["https://iili.io/fubYjMx.webp"],
      },
      {
        dni: "55544566",
        nombres: "Silvia",
        apellidos: "Ortiz Cabrera",
        nombreCompleto: "Silvia Ortiz Cabrera",
        numeroLicencia: "Q11345678",
        claseLicencia: "A",
        categoriaLicencia: "Uno",
        fotocheck: ["https://iili.io/fubYw6Q.webp"],
      },
      {
        dni: "66655677",
        nombres: "Hector",
        apellidos: "Velasquez Marin",
        nombreCompleto: "Hector Velasquez Marin",
        numeroLicencia: "Q11456789",
        claseLicencia: "B",
        categoriaLicencia: "Dos",
        fotocheck: ["https://iili.io/fubYOFV.webp"],
      },
      {
        dni: "77766788",
        nombres: "Gloria",
        apellidos: "Cardenas Torres",
        nombreCompleto: "Gloria Cardenas Torres",
        numeroLicencia: "Q11567890",
        claseLicencia: "A",
        categoriaLicencia: "Tres",
        fotocheck: ["https://iili.io/fubYecB.webp"],
      },
      {
        dni: "88877899",
        nombres: "Andres",
        apellidos: "Romero Davila",
        nombreCompleto: "Andres Romero Davila",
        numeroLicencia: "Q11678901",
        claseLicencia: "B",
        categoriaLicencia: "Uno",
        fotocheck: ["https://iili.io/fubYk8P.webp"],
      },
      {
        dni: "99988900",
        nombres: "Natalia",
        apellidos: "Silva Campos",
        nombreCompleto: "Natalia Silva Campos",
        numeroLicencia: "Q11789012",
        claseLicencia: "A",
        categoriaLicencia: "Dos",
        fotocheck: ["https://iili.io/fubYSAF.webp"],
      },
      {
        dni: "10099011",
        nombres: "Rodrigo",
        apellidos: "Vega Morales",
        nombreCompleto: "Rodrigo Vega Morales",
        numeroLicencia: "Q11890123",
        claseLicencia: "B",
        categoriaLicencia: "Tres",
        fotocheck: ["https://iili.io/fubYSAF.webp"],
      },
    ])
    .returning();

  console.log("✅ Drivers inserted");
  return driversData;
}
