import { database } from "@db/connection.db";
import { mantenimientos } from "@model/tables/mantenimiento.model";
import { Vehiculo } from "@model/tables/vehiculo.model";
import { getDateString } from "@function/date.function";

export async function seedMantenimientos(vehiclesData: Vehiculo[]) {
  console.log("🌱 Seeding maintenances...");

  if (vehiclesData.length === 0) {
    console.log("⚠️ Skipping maintenances (no vehicles)");
    return;
  }

  await database.insert(mantenimientos).values([
    {
      vehiculoId: vehiclesData[0].id,
      tipo: "preventivo",
      costo: "200.00",
      descripcion: "Cambio de aceite y revision general",
      fecha: getDateString(-90),
      kilometraje: 45000,
      proveedor: "Taller Mecanico Express",
    },
    {
      vehiculoId: vehiclesData[1].id,
      tipo: "correctivo",
      costo: "850.00",
      descripcion: "Diagnostico y reparacion de motor",
      fecha: getDateString(-85),
      kilometraje: 52000,
      proveedor: "Motor Service Center",
    },
    {
      vehiculoId: vehiclesData[2].id,
      tipo: "correctivo",
      costo: "1500.00",
      descripcion: "Reemplazo de frenos",
      fecha: getDateString(-80),
      kilometraje: 78000,
      proveedor: "Frenos y Mas",
    },
    {
      vehiculoId: vehiclesData[3].id,
      tipo: "preventivo",
      costo: "350.00",
      descripcion: "Rotacion de neumaticos y alineacion",
      fecha: getDateString(-75),
      kilometraje: 19000,
      proveedor: "Taller Mecanico Express",
    },
    {
      vehiculoId: vehiclesData[4].id,
      tipo: "preventivo",
      costo: "180.00",
      descripcion: "Reemplazo de filtro de aire",
      fecha: getDateString(-70),
      kilometraje: 44000,
      proveedor: "Motor Service Center",
    },
    {
      vehiculoId: vehiclesData[5].id,
      tipo: "preventivo",
      costo: "420.00",
      descripcion: "Cambio de liquido de transmision",
      fecha: getDateString(-65),
      kilometraje: 69000,
      proveedor: "Frenos y Mas",
    },
    {
      vehiculoId: vehiclesData[6].id,
      tipo: "preventivo",
      costo: "280.00",
      descripcion: "Revision y reemplazo de bateria",
      fecha: getDateString(-60),
      kilometraje: 34000,
      proveedor: "Taller Mecanico Express",
    },
    {
      vehiculoId: vehiclesData[7].id,
      tipo: "correctivo",
      costo: "650.00",
      descripcion: "Reparacion de suspension",
      fecha: getDateString(-55),
      kilometraje: 54000,
      proveedor: "Motor Service Center",
    },
    {
      vehiculoId: vehiclesData[8].id,
      tipo: "correctivo",
      costo: "920.00",
      descripcion: "Reparacion de sistema de escape",
      fecha: getDateString(-50),
      kilometraje: 94000,
      proveedor: "Frenos y Mas",
    },
    {
      vehiculoId: vehiclesData[9].id,
      tipo: "preventivo",
      costo: "250.00",
      descripcion: "Cambio de bujias",
      fecha: getDateString(-45),
      kilometraje: 27000,
      proveedor: "Taller Mecanico Express",
    },
    {
      vehiculoId: vehiclesData[10].id,
      tipo: "preventivo",
      costo: "320.00",
      descripcion: "Revision de sistema de frenos",
      fecha: getDateString(-40),
      kilometraje: 14000,
      proveedor: "Motor Service Center",
    },
    {
      vehiculoId: vehiclesData[11].id,
      tipo: "correctivo",
      costo: "780.00",
      descripcion: "Reparacion de embrague",
      fecha: getDateString(-35),
      kilometraje: 47000,
      proveedor: "Frenos y Mas",
    },
    {
      vehiculoId: vehiclesData[12].id,
      tipo: "preventivo",
      costo: "190.00",
      descripcion: "Cambio de filtro de combustible",
      fecha: getDateString(-30),
      kilometraje: 31000,
      proveedor: "Taller Mecanico Express",
    },
    {
      vehiculoId: vehiclesData[13].id,
      tipo: "preventivo",
      costo: "410.00",
      descripcion: "Revision de sistema electrico",
      fecha: getDateString(-28),
      kilometraje: 74000,
      proveedor: "Motor Service Center",
    },
    {
      vehiculoId: vehiclesData[14].id,
      tipo: "correctivo",
      costo: "1100.00",
      descripcion: "Reparacion de caja de cambios",
      fecha: getDateString(-26),
      kilometraje: 51000,
      proveedor: "Frenos y Mas",
    },
    {
      vehiculoId: vehiclesData[15].id,
      tipo: "preventivo",
      costo: "270.00",
      descripcion: "Revision general de motor",
      fecha: getDateString(-24),
      kilometraje: 87000,
      proveedor: "Taller Mecanico Express",
    },
    {
      vehiculoId: vehiclesData[16].id,
      tipo: "preventivo",
      costo: "330.00",
      descripcion: "Cambio de correa de distribucion",
      fecha: getDateString(-22),
      kilometraje: 37000,
      proveedor: "Motor Service Center",
    },
    {
      vehiculoId: vehiclesData[17].id,
      tipo: "correctivo",
      costo: "890.00",
      descripcion: "Reparacion de direccion",
      fecha: getDateString(-20),
      kilometraje: 17000,
      proveedor: "Frenos y Mas",
    },
    {
      vehiculoId: vehiclesData[18].id,
      tipo: "preventivo",
      costo: "220.00",
      descripcion: "Cambio de liquido de frenos",
      fecha: getDateString(-18),
      kilometraje: 67000,
      proveedor: "Taller Mecanico Express",
    },
    {
      vehiculoId: vehiclesData[19].id,
      tipo: "preventivo",
      costo: "380.00",
      descripcion: "Revision de sistema de refrigeracion",
      fecha: getDateString(-16),
      kilometraje: 41000,
      proveedor: "Motor Service Center",
    },
    {
      vehiculoId: vehiclesData[20].id,
      tipo: "correctivo",
      costo: "1200.00",
      descripcion: "Reparacion de turbo",
      fecha: getDateString(-14),
      kilometraje: 24000,
      proveedor: "Frenos y Mas",
    },
    {
      vehiculoId: vehiclesData[21].id,
      tipo: "preventivo",
      costo: "290.00",
      descripcion: "Cambio de aceite de transmision",
      fecha: getDateString(-12),
      kilometraje: 57000,
      proveedor: "Taller Mecanico Express",
    },
    {
      vehiculoId: vehiclesData[22].id,
      tipo: "preventivo",
      costo: "340.00",
      descripcion: "Revision de amortiguadores",
      fecha: getDateString(-10),
      kilometraje: 71000,
      proveedor: "Motor Service Center",
    },
    {
      vehiculoId: vehiclesData[23].id,
      tipo: "correctivo",
      costo: "950.00",
      descripcion: "Reparacion de sistema de inyeccion",
      fecha: getDateString(-8),
      kilometraje: 11000,
      proveedor: "Frenos y Mas",
    },
    {
      vehiculoId: vehiclesData[24].id,
      tipo: "preventivo",
      costo: "240.00",
      descripcion: "Cambio de pastillas de freno",
      fecha: getDateString(-6),
      kilometraje: 35000,
      proveedor: "Taller Mecanico Express",
    },
    {
      vehiculoId: vehiclesData[25].id,
      tipo: "preventivo",
      costo: "360.00",
      descripcion: "Revision de sistema de escape",
      fecha: getDateString(-4),
      kilometraje: 61000,
      proveedor: "Motor Service Center",
    },
    {
      vehiculoId: vehiclesData[26].id,
      tipo: "correctivo",
      costo: "1050.00",
      descripcion: "Reparacion de motor",
      fecha: getDateString(-2),
      kilometraje: 77000,
      proveedor: "Frenos y Mas",
    },
    {
      vehiculoId: vehiclesData[27].id,
      tipo: "preventivo",
      costo: "310.00",
      descripcion: "Cambio de filtros",
      fecha: getDateString(0),
      kilometraje: 39000,
      proveedor: "Taller Mecanico Express",
    },
    {
      vehiculoId: vehiclesData[28].id,
      tipo: "preventivo",
      costo: "400.00",
      descripcion: "Revision completa programada",
      fecha: getDateString(5),
      kilometraje: 53000,
      proveedor: "Motor Service Center",
    },
    {
      vehiculoId: vehiclesData[29].id,
      tipo: "preventivo",
      costo: "260.00",
      descripcion: "Mantenimiento preventivo general",
      fecha: getDateString(10),
      kilometraje: 21000,
      proveedor: "Frenos y Mas",
    },
  ]);

  console.log("✅ Maintenances inserted");
}
