import { database } from "@db/connection.db";
import { mantenimientos } from "@model/tables/mantenimiento.model";
import { Taller } from "@model/tables/taller.model";
import { Vehiculo } from "@model/tables/vehiculo.model";
import { getDate } from "@function/date.function";

export async function seedMantenimientos(
  vehiclesData: Vehiculo[],
  talleresData: Taller[]
) {
  console.log("🌱 Seeding maintenances...");

  if (vehiclesData.length === 0) {
    console.log("⚠️ Skipping maintenances (no vehicles)");
    return;
  }

  if (talleresData.length === 0) {
    console.log("⚠️ Skipping maintenances (no workshops)");
    return;
  }

  const tallerExpress = talleresData.find(
    (t) => t.nombreComercial === "Taller Mecanico Express"
  );
  const tallerMotor = talleresData.find(
    (t) => t.nombreComercial === "Motor Service Center"
  );
  const tallerFrenos = talleresData.find(
    (t) => t.nombreComercial === "Frenos y Mas"
  );

  // 2. Crear Mantenimientos
  await database.insert(mantenimientos).values([
    {
      vehiculoId: vehiclesData[0].id,
      tallerId: tallerExpress!.id,
      tipo: "preventivo",
      costoTotal: "200.00",
      descripcion: "Cambio de aceite y revision general",
      fechaIngreso: getDate(-90),
      kilometraje: 45000,
      estado: "finalizado",
      codigoOrden: "ORD-001",
    },
    {
      vehiculoId: vehiclesData[1].id,
      tallerId: tallerMotor!.id,
      tipo: "correctivo",
      costoTotal: "850.00",
      descripcion: "Diagnostico y reparacion de motor",
      fechaIngreso: getDate(-85),
      kilometraje: 52000,
      estado: "finalizado",
      codigoOrden: "ORD-002",
    },
    {
      vehiculoId: vehiclesData[2].id,
      tallerId: tallerFrenos!.id,
      tipo: "correctivo",
      costoTotal: "1500.00",
      descripcion: "Reemplazo de frenos",
      fechaIngreso: getDate(-80),
      kilometraje: 78000,
      estado: "finalizado",
      codigoOrden: "ORD-003",
    },
    {
      vehiculoId: vehiclesData[3].id,
      tallerId: tallerExpress!.id,
      tipo: "preventivo",
      costoTotal: "350.00",
      descripcion: "Rotacion de neumaticos y alineacion",
      fechaIngreso: getDate(-75),
      kilometraje: 19000,
      estado: "finalizado",
      codigoOrden: "ORD-004",
    },
    {
      vehiculoId: vehiclesData[4].id,
      tallerId: tallerMotor!.id,
      tipo: "preventivo",
      costoTotal: "180.00",
      descripcion: "Reemplazo de filtro de aire",
      fechaIngreso: getDate(-70),
      kilometraje: 44000,
      estado: "finalizado",
      codigoOrden: "ORD-005",
    },
    {
      vehiculoId: vehiclesData[5].id,
      tallerId: tallerFrenos!.id,
      tipo: "preventivo",
      costoTotal: "420.00",
      descripcion: "Cambio de liquido de transmision",
      fechaIngreso: getDate(-65),
      kilometraje: 69000,
      estado: "finalizado",
      codigoOrden: "ORD-006",
    },
    {
      vehiculoId: vehiclesData[6].id,
      tallerId: tallerExpress!.id,
      tipo: "preventivo",
      costoTotal: "280.00",
      descripcion: "Revision y reemplazo de bateria",
      fechaIngreso: getDate(-60),
      kilometraje: 34000,
      estado: "finalizado",
      codigoOrden: "ORD-007",
    },
    {
      vehiculoId: vehiclesData[7].id,
      tallerId: tallerMotor!.id,
      tipo: "correctivo",
      costoTotal: "650.00",
      descripcion: "Reparacion de suspension",
      fechaIngreso: getDate(-55),
      kilometraje: 54000,
      estado: "finalizado",
      codigoOrden: "ORD-008",
    },
    {
      vehiculoId: vehiclesData[8].id,
      tallerId: tallerFrenos!.id,
      tipo: "correctivo",
      costoTotal: "920.00",
      descripcion: "Reparacion de sistema de escape",
      fechaIngreso: getDate(-50),
      kilometraje: 94000,
      estado: "finalizado",
      codigoOrden: "ORD-009",
    },
    {
      vehiculoId: vehiclesData[9].id,
      tallerId: tallerExpress!.id,
      tipo: "preventivo",
      costoTotal: "250.00",
      descripcion: "Cambio de bujias",
      fechaIngreso: getDate(-45),
      kilometraje: 27000,
      estado: "finalizado",
      codigoOrden: "ORD-010",
    },
    {
      vehiculoId: vehiclesData[10].id,
      tallerId: tallerMotor!.id,
      tipo: "preventivo",
      costoTotal: "320.00",
      descripcion: "Revision de sistema de frenos",
      fechaIngreso: getDate(-40),
      kilometraje: 14000,
      estado: "finalizado",
      codigoOrden: "ORD-011",
    },
    {
      vehiculoId: vehiclesData[11].id,
      tallerId: tallerFrenos!.id,
      tipo: "correctivo",
      costoTotal: "780.00",
      descripcion: "Reparacion de embrague",
      fechaIngreso: getDate(-35),
      kilometraje: 47000,
      estado: "finalizado",
      codigoOrden: "ORD-012",
    },
    {
      vehiculoId: vehiclesData[12].id,
      tallerId: tallerExpress!.id,
      tipo: "preventivo",
      costoTotal: "190.00",
      descripcion: "Cambio de filtro de combustible",
      fechaIngreso: getDate(-30),
      kilometraje: 31000,
      estado: "finalizado",
      codigoOrden: "ORD-013",
    },
    {
      vehiculoId: vehiclesData[13].id,
      tallerId: tallerMotor!.id,
      tipo: "preventivo",
      costoTotal: "410.00",
      descripcion: "Revision de sistema electrico",
      fechaIngreso: getDate(-28),
      kilometraje: 74000,
      estado: "finalizado",
      codigoOrden: "ORD-014",
    },
    {
      vehiculoId: vehiclesData[14].id,
      tallerId: tallerFrenos!.id,
      tipo: "correctivo",
      costoTotal: "1100.00",
      descripcion: "Reparacion de caja de cambios",
      fechaIngreso: getDate(-26),
      kilometraje: 51000,
      estado: "finalizado",
      codigoOrden: "ORD-015",
    },
    {
      vehiculoId: vehiclesData[15].id,
      tallerId: tallerExpress!.id,
      tipo: "preventivo",
      costoTotal: "270.00",
      descripcion: "Revision general de motor",
      fechaIngreso: getDate(-24),
      kilometraje: 87000,
      estado: "finalizado",
      codigoOrden: "ORD-016",
    },
    {
      vehiculoId: vehiclesData[16].id,
      tallerId: tallerMotor!.id,
      tipo: "preventivo",
      costoTotal: "330.00",
      descripcion: "Cambio de correa de distribucion",
      fechaIngreso: getDate(-22),
      kilometraje: 37000,
      estado: "finalizado",
      codigoOrden: "ORD-017",
    },
    {
      vehiculoId: vehiclesData[17].id,
      tallerId: tallerFrenos!.id,
      tipo: "correctivo",
      costoTotal: "890.00",
      descripcion: "Reparacion de direccion",
      fechaIngreso: getDate(-20),
      kilometraje: 17000,
      estado: "finalizado",
      codigoOrden: "ORD-018",
    },
    {
      vehiculoId: vehiclesData[18].id,
      tallerId: tallerExpress!.id,
      tipo: "preventivo",
      costoTotal: "220.00",
      descripcion: "Cambio de liquido de frenos",
      fechaIngreso: getDate(-18),
      kilometraje: 67000,
      estado: "finalizado",
      codigoOrden: "ORD-019",
    },
    {
      vehiculoId: vehiclesData[19].id,
      tallerId: tallerMotor!.id,
      tipo: "preventivo",
      costoTotal: "380.00",
      descripcion: "Revision de sistema de refrigeracion",
      fechaIngreso: getDate(-16),
      kilometraje: 41000,
      estado: "finalizado",
      codigoOrden: "ORD-020",
    },
    {
      vehiculoId: vehiclesData[20].id,
      tallerId: tallerFrenos!.id,
      tipo: "correctivo",
      costoTotal: "1200.00",
      descripcion: "Reparacion de turbo",
      fechaIngreso: getDate(-14),
      kilometraje: 24000,
      estado: "finalizado",
      codigoOrden: "ORD-021",
    },
    {
      vehiculoId: vehiclesData[21].id,
      tallerId: tallerExpress!.id,
      tipo: "preventivo",
      costoTotal: "290.00",
      descripcion: "Cambio de aceite de transmision",
      fechaIngreso: getDate(-12),
      kilometraje: 57000,
      estado: "finalizado",
      codigoOrden: "ORD-022",
    },
    {
      vehiculoId: vehiclesData[22].id,
      tallerId: tallerMotor!.id,
      tipo: "preventivo",
      costoTotal: "340.00",
      descripcion: "Revision de amortiguadores",
      fechaIngreso: getDate(-10),
      kilometraje: 71000,
      estado: "finalizado",
      codigoOrden: "ORD-023",
    },
    {
      vehiculoId: vehiclesData[23].id,
      tallerId: tallerFrenos!.id,
      tipo: "correctivo",
      costoTotal: "950.00",
      descripcion: "Reparacion de sistema de inyeccion",
      fechaIngreso: getDate(-8),
      kilometraje: 11000,
      estado: "finalizado",
      codigoOrden: "ORD-024",
    },
    {
      vehiculoId: vehiclesData[24].id,
      tallerId: tallerExpress!.id,
      tipo: "preventivo",
      costoTotal: "240.00",
      descripcion: "Cambio de pastillas de freno",
      fechaIngreso: getDate(-6),
      kilometraje: 35000,
      estado: "finalizado",
      codigoOrden: "ORD-025",
    },
    {
      vehiculoId: vehiclesData[25].id,
      tallerId: tallerMotor!.id,
      tipo: "preventivo",
      costoTotal: "360.00",
      descripcion: "Revision de sistema de escape",
      fechaIngreso: getDate(-4),
      kilometraje: 61000,
      estado: "finalizado",
      codigoOrden: "ORD-026",
    },
    {
      vehiculoId: vehiclesData[26].id,
      tallerId: tallerFrenos!.id,
      tipo: "correctivo",
      costoTotal: "1050.00",
      descripcion: "Reparacion de motor",
      fechaIngreso: getDate(-2),
      kilometraje: 77000,
      estado: "finalizado",
      codigoOrden: "ORD-027",
    },
    {
      vehiculoId: vehiclesData[27].id,
      tallerId: tallerExpress!.id,
      tipo: "preventivo",
      costoTotal: "310.00",
      descripcion: "Cambio de filtros",
      fechaIngreso: getDate(0),
      kilometraje: 39000,
      estado: "pendiente",
      codigoOrden: "ORD-028",
    },
    {
      vehiculoId: vehiclesData[28].id,
      tallerId: tallerMotor!.id,
      tipo: "preventivo",
      costoTotal: "400.00",
      descripcion: "Revision completa programada",
      fechaIngreso: getDate(5),
      kilometraje: 53000,
      estado: "pendiente",
      codigoOrden: "ORD-029",
    },
    {
      vehiculoId: vehiclesData[29].id,
      tallerId: tallerFrenos!.id,
      tipo: "preventivo",
      costoTotal: "260.00",
      descripcion: "Mantenimiento preventivo general",
      fechaIngreso: getDate(10),
      kilometraje: 21000,
      estado: "pendiente",
      codigoOrden: "ORD-030",
    },
  ]);

  console.log("✅ Maintenances inserted");
}
