import { database } from "@db/connection.db";
import { usuarios } from "@model/tables/usuario.model";
import * as bcrypt from "bcrypt";

export async function seedUsuarios() {
  console.log("🌱 Seeding users...");

  const hashedPassword = await bcrypt.hash("123456", 10);

  const usersData = await database
    .insert(usuarios)
    .values([
      {
        nombres: "Erick Stip",
        apellidos: "Flores Santos",
        nombreCompleto: "Erick Stip Flores Santos",
        email: "erick@gmail.com",
        contrasenia: hashedPassword,
        roles: ["admin"],
      },
      {
        nombres: "Clive",
        apellidos: "Ñahui Xesppe",
        nombreCompleto: "Clive Ñahui Xesppe",
        email: "clive@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Sofia",
        apellidos: "Martinez Lopez",
        nombreCompleto: "Sofia Martinez Lopez",
        email: "sofia.martinez@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Diego",
        apellidos: "Ramirez Torres",
        nombreCompleto: "Diego Ramirez Torres",
        email: "diego.ramirez@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Valentina",
        apellidos: "Gonzalez Silva",
        nombreCompleto: "Valentina Gonzalez Silva",
        email: "valentina.gonzalez@gmail.com",
        contrasenia: hashedPassword,
        roles: ["admin"],
      },
      {
        nombres: "Lucas",
        apellidos: "Fernandez Castro",
        nombreCompleto: "Lucas Fernandez Castro",
        email: "lucas.fernandez@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Isabella",
        apellidos: "Rodriguez Diaz",
        nombreCompleto: "Isabella Rodriguez Diaz",
        email: "isabella.rodriguez@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Mateo",
        apellidos: "Vargas Mendoza",
        nombreCompleto: "Mateo Vargas Mendoza",
        email: "mateo.vargas@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Camila",
        apellidos: "Rojas Huaman",
        nombreCompleto: "Camila Rojas Huaman",
        email: "camila.rojas@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Santiago",
        apellidos: "Torres Diaz",
        nombreCompleto: "Santiago Torres Diaz",
        email: "santiago.torres@gmail.com",
        contrasenia: hashedPassword,
        roles: ["admin"],
      },
      {
        nombres: "Emma",
        apellidos: "Ramirez Flores",
        nombreCompleto: "Emma Ramirez Flores",
        email: "emma.ramirez@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Benjamin",
        apellidos: "Castro Medina",
        nombreCompleto: "Benjamin Castro Medina",
        email: "benjamin.castro@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Mia",
        apellidos: "Sanchez Ramos",
        nombreCompleto: "Mia Sanchez Ramos",
        email: "mia.sanchez@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Sebastian",
        apellidos: "Morales Cruz",
        nombreCompleto: "Sebastian Morales Cruz",
        email: "sebastian.morales@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Martina",
        apellidos: "Vega Silva",
        nombreCompleto: "Martina Vega Silva",
        email: "martina.vega@gmail.com",
        contrasenia: hashedPassword,
        roles: ["admin"],
      },
      {
        nombres: "Nicolas",
        apellidos: "Jimenez Paredes",
        nombreCompleto: "Nicolas Jimenez Paredes",
        email: "nicolas.jimenez@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Lucia",
        apellidos: "Nunez Castillo",
        nombreCompleto: "Lucia Nunez Castillo",
        email: "lucia.nunez@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Matias",
        apellidos: "Herrera Campos",
        nombreCompleto: "Matias Herrera Campos",
        email: "matias.herrera@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Victoria",
        apellidos: "Ponce Rojas",
        nombreCompleto: "Victoria Ponce Rojas",
        email: "victoria.ponce@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Thiago",
        apellidos: "Salazar Mora",
        nombreCompleto: "Thiago Salazar Mora",
        email: "thiago.salazar@gmail.com",
        contrasenia: hashedPassword,
        roles: ["admin"],
      },
      {
        nombres: "Renata",
        apellidos: "Rios Gutierrez",
        nombreCompleto: "Renata Rios Gutierrez",
        email: "renata.rios@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Gabriel",
        apellidos: "Mendez Luna",
        nombreCompleto: "Gabriel Mendez Luna",
        email: "gabriel.mendez@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Catalina",
        apellidos: "Ochoa Suarez",
        nombreCompleto: "Catalina Ochoa Suarez",
        email: "catalina.ochoa@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Joaquin",
        apellidos: "Reyes Paz",
        nombreCompleto: "Joaquin Reyes Paz",
        email: "joaquin.reyes@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Antonella",
        apellidos: "Flores Vera",
        nombreCompleto: "Antonella Flores Vera",
        email: "antonella.flores@gmail.com",
        contrasenia: hashedPassword,
        roles: ["admin"],
      },
      {
        nombres: "Felipe",
        apellidos: "Acosta Lozano",
        nombreCompleto: "Felipe Acosta Lozano",
        email: "felipe.acosta@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Valeria",
        apellidos: "Miranda Valle",
        nombreCompleto: "Valeria Miranda Valle",
        email: "valeria.miranda@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Emiliano",
        apellidos: "Campos Arias",
        nombreCompleto: "Emiliano Campos Arias",
        email: "emiliano.campos@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Julieta",
        apellidos: "Leon Santos",
        nombreCompleto: "Julieta Leon Santos",
        email: "julieta.leon@gmail.com",
        contrasenia: hashedPassword,
        roles: ["empleado"],
      },
      {
        nombres: "Samuel",
        apellidos: "Parra Gamboa",
        nombreCompleto: "Samuel Parra Gamboa",
        email: "samuel.parra@gmail.com",
        contrasenia: hashedPassword,
        roles: ["admin"],
      },
    ])
    .returning();

  console.log("✅ Users inserted");
  return usersData;
}
