import { database } from "@db/connection.db";
import { vehiculos } from "@model/tables/vehiculo.model";

export async function seedVehiculos() {
  console.log("🌱 Seeding vehicles...");

  const vehiclesData = await database
    .insert(vehiculos)
    .values([
      {
        placa: "ABC123",
        codigoInterno: "0001",
        marca: "Toyota",
        modelo: "Corolla",
        anio: 2020,
        kilometraje: 50000,
        estado: "activo",
        imagenes: ["https://iili.io/fubanob.jpg"],
      },
      {
        placa: "XYZ789",
        codigoInterno: "0002",
        marca: "Hyundai",
        modelo: "Elantra",
        anio: 2021,
        kilometraje: 30000,
        estado: "activo",
        imagenes: ["https://iili.io/fubaxix.jpg"],
      },
      {
        placa: "DEF456",
        codigoInterno: "0003",
        marca: "Nissan",
        modelo: "Sentra",
        anio: 2019,
        kilometraje: 80000,
        estado: "taller",
        imagenes: ["https://iili.io/fubauUB.jpg"],
      },
      {
        placa: "GHI321",
        codigoInterno: "0004",
        marca: "Honda",
        modelo: "Civic",
        anio: 2022,
        kilometraje: 20000,
        estado: "activo",
        imagenes: ["https://iili.io/fuba5R1.jpg"],
      },
      {
        placa: "JKL654",
        codigoInterno: "0005",
        marca: "Mazda",
        modelo: "3",
        anio: 2020,
        kilometraje: 45000,
        estado: "activo",
        imagenes: ["https://iili.io/fubaYDg.jpg"],
      },
      {
        placa: "MNO987",
        codigoInterno: "0006",
        marca: "Chevrolet",
        modelo: "Cruze",
        anio: 2019,
        kilometraje: 70000,
        estado: "activo",
        imagenes: ["https://iili.io/fubaEfR.jpg"],
      },
      {
        placa: "PQR234",
        codigoInterno: "0007",
        marca: "Kia",
        modelo: "Forte",
        anio: 2021,
        kilometraje: 35000,
        estado: "activo",
        imagenes: ["https://iili.io/fubaWJI.jpg"],
      },
      {
        placa: "STU567",
        codigoInterno: "0008",
        marca: "Volkswagen",
        modelo: "Jetta",
        anio: 2020,
        kilometraje: 55000,
        estado: "taller",
        imagenes: ["https://iili.io/fubaXRt.jpg"],
      },
      {
        placa: "VWX890",
        codigoInterno: "0009",
        marca: "Ford",
        modelo: "Focus",
        anio: 2018,
        kilometraje: 95000,
        estado: "activo",
        imagenes: ["https://iili.io/fubahOX.jpg"],
      },
      {
        placa: "YZA123",
        codigoInterno: "0010",
        marca: "Suzuki",
        modelo: "Ciaz",
        anio: 2021,
        kilometraje: 28000,
        estado: "activo",
        imagenes: ["https://iili.io/fubaNxs.jpg"],
      },
      {
        placa: "BCD456",
        codigoInterno: "0011",
        marca: "Toyota",
        modelo: "Yaris",
        anio: 2022,
        kilometraje: 15000,
        estado: "activo",
        imagenes: ["https://iili.io/fubavf4.webp"],
      },
      {
        placa: "EFG789",
        codigoInterno: "0012",
        marca: "Hyundai",
        modelo: "Accent",
        anio: 2020,
        kilometraje: 48000,
        estado: "activo",
        imagenes: ["https://iili.io/fuba80l.webp"],
      },
      {
        placa: "HIJ012",
        codigoInterno: "0013",
        marca: "Nissan",
        modelo: "Versa",
        anio: 2021,
        kilometraje: 32000,
        estado: "activo",
        imagenes: ["https://iili.io/fubaSg2.webp"],
      },
      {
        placa: "KLM345",
        codigoInterno: "0014",
        marca: "Honda",
        modelo: "City",
        anio: 2019,
        kilometraje: 75000,
        estado: "activo",
        imagenes: ["https://iili.io/fubar57.webp"],
      },
      {
        placa: "NOP678",
        codigoInterno: "0015",
        marca: "Mazda",
        modelo: "2",
        anio: 2020,
        kilometraje: 52000,
        estado: "activo",
        imagenes: ["https://iili.io/fuba4e9.webp"],
      },
      {
        placa: "QRS901",
        codigoInterno: "0016",
        marca: "Chevrolet",
        modelo: "Sail",
        anio: 2018,
        kilometraje: 88000,
        estado: "taller",
        imagenes: ["https://iili.io/fubaizu.webp"],
      },
      {
        placa: "TUV234",
        codigoInterno: "0017",
        marca: "Kia",
        modelo: "Rio",
        anio: 2021,
        kilometraje: 38000,
        estado: "activo",
        imagenes: ["https://iili.io/fubasWb.webp"],
      },
      {
        placa: "WXY567",
        codigoInterno: "0018",
        marca: "Volkswagen",
        modelo: "Polo",
        anio: 2022,
        kilometraje: 18000,
        estado: "activo",
        imagenes: ["https://iili.io/fubaZqx.webp"],
      },
      {
        placa: "ZAB890",
        codigoInterno: "0019",
        marca: "Ford",
        modelo: "Fiesta",
        anio: 2019,
        kilometraje: 68000,
        estado: "activo",
        imagenes: ["https://iili.io/fubaDgV.webp"],
      },
      {
        placa: "CDE123",
        codigoInterno: "0020",
        marca: "Suzuki",
        modelo: "Swift",
        anio: 2020,
        kilometraje: 42000,
        estado: "activo",
        imagenes: ["https://iili.io/fubamdB.webp"],
      },
      {
        placa: "FGH456",
        codigoInterno: "0021",
        marca: "Toyota",
        modelo: "Camry",
        anio: 2021,
        kilometraje: 25000,
        estado: "activo",
        imagenes: ["https://iili.io/fubaye1.webp"],
      },
      {
        placa: "IJK789",
        codigoInterno: "0022",
        marca: "Hyundai",
        modelo: "Sonata",
        anio: 2020,
        kilometraje: 58000,
        estado: "activo",
        imagenes: ["https://iili.io/fubc9mF.webp"],
      },
      {
        placa: "LMN012",
        codigoInterno: "0023",
        marca: "Nissan",
        modelo: "Altima",
        anio: 2019,
        kilometraje: 72000,
        estado: "activo",
        imagenes: ["https://iili.io/fubcdXa.webp"],
      },
      {
        placa: "OPQ345",
        codigoInterno: "0024",
        marca: "Honda",
        modelo: "Accord",
        anio: 2022,
        kilometraje: 12000,
        estado: "activo",
        imagenes: ["https://iili.io/fubc2LJ.webp"],
      },
      {
        placa: "RST678",
        codigoInterno: "0025",
        marca: "Mazda",
        modelo: "6",
        anio: 2021,
        kilometraje: 36000,
        estado: "activo",
        imagenes: ["https://iili.io/fubcBdN.webp"],
      },
      {
        placa: "UVW901",
        codigoInterno: "0026",
        marca: "Chevrolet",
        modelo: "Malibu",
        anio: 2020,
        kilometraje: 62000,
        estado: "activo",
        imagenes: ["https://iili.io/fubcnet.webp"],
      },
      {
        placa: "XYZ234",
        codigoInterno: "0027",
        marca: "Kia",
        modelo: "Optima",
        anio: 2019,
        kilometraje: 78000,
        estado: "taller",
        imagenes: ["https://iili.io/fubczIn.webp"],
      },
      {
        placa: "ABC567",
        codigoInterno: "0028",
        marca: "Volkswagen",
        modelo: "Passat",
        anio: 2021,
        kilometraje: 40000,
        estado: "activo",
        imagenes: ["https://iili.io/fubcTLG.webp"],
      },
      {
        placa: "DEF890",
        codigoInterno: "0029",
        marca: "Ford",
        modelo: "Fusion",
        anio: 2020,
        kilometraje: 54000,
        estado: "activo",
        imagenes: ["https://iili.io/fubc5rl.webp"],
      },
      {
        placa: "GHI123",
        codigoInterno: "0030",
        marca: "Suzuki",
        modelo: "Baleno",
        anio: 2022,
        kilometraje: 22000,
        estado: "activo",
        imagenes: ["https://iili.io/fubcY22.webp"],
      },
    ])
    .returning();

  console.log("✅ Vehicles inserted");
  return vehiclesData;
}
