import { database } from "@db/connection.db";
import { vehiculos } from "@model/tables/vehiculo.model";
import { getDateString } from "@function/date.function";

export async function seedVehiculos() {
  console.log("🌱 Seeding vehicles...");

  const vehiclesData = await database
    .insert(vehiculos)
    .values([
      {
        placa: "ABC-123",
        marca: "Toyota",
        modelo: "Corolla",
        anio: 2020,
        kilometraje: 50000,
        fechaVencimientoSoat: getDateString(90),
        estado: "activo",
        imagenes: ["https://iili.io/fubanob.jpg"],
      },
      {
        placa: "XYZ-789",
        marca: "Hyundai",
        modelo: "Elantra",
        anio: 2021,
        kilometraje: 30000,
        fechaVencimientoSoat: getDateString(180),
        estado: "activo",
        imagenes: ["https://iili.io/fubaxix.jpg"],
      },
      {
        placa: "DEF-456",
        marca: "Nissan",
        modelo: "Sentra",
        anio: 2019,
        kilometraje: 80000,
        fechaVencimientoSoat: getDateString(-15),
        estado: "taller",
        imagenes: ["https://iili.io/fubauUB.jpg"],
      },
      {
        placa: "GHI-321",
        marca: "Honda",
        modelo: "Civic",
        anio: 2022,
        kilometraje: 20000,
        fechaVencimientoSoat: getDateString(120),
        estado: "activo",
        imagenes: ["https://iili.io/fuba5R1.jpg"],
      },
      {
        placa: "JKL-654",
        marca: "Mazda",
        modelo: "3",
        anio: 2020,
        kilometraje: 45000,
        fechaVencimientoSoat: getDateString(150),
        estado: "activo",
        imagenes: ["https://iili.io/fubaYDg.jpg"],
      },
      {
        placa: "MNO-987",
        marca: "Chevrolet",
        modelo: "Cruze",
        anio: 2019,
        kilometraje: 70000,
        fechaVencimientoSoat: getDateString(60),
        estado: "activo",
        imagenes: ["https://iili.io/fubaEfR.jpg"],
      },
      {
        placa: "PQR-234",
        marca: "Kia",
        modelo: "Forte",
        anio: 2021,
        kilometraje: 35000,
        fechaVencimientoSoat: getDateString(200),
        estado: "activo",
        imagenes: ["https://iili.io/fubaWJI.jpg"],
      },
      {
        placa: "STU-567",
        marca: "Volkswagen",
        modelo: "Jetta",
        anio: 2020,
        kilometraje: 55000,
        fechaVencimientoSoat: getDateString(-5),
        estado: "taller",
        imagenes: ["https://iili.io/fubaXRt.jpg"],
      },
      {
        placa: "VWX-890",
        marca: "Ford",
        modelo: "Focus",
        anio: 2018,
        kilometraje: 95000,
        fechaVencimientoSoat: getDateString(30),
        estado: "activo",
        imagenes: ["https://iili.io/fubahOX.jpg"],
      },
      {
        placa: "YZA-123",
        marca: "Suzuki",
        modelo: "Ciaz",
        anio: 2021,
        kilometraje: 28000,
        fechaVencimientoSoat: getDateString(170),
        estado: "activo",
        imagenes: ["https://iili.io/fubaNxs.jpg"],
      },
      {
        placa: "BCD-456",
        marca: "Toyota",
        modelo: "Yaris",
        anio: 2022,
        kilometraje: 15000,
        fechaVencimientoSoat: getDateString(250),
        estado: "activo",
        imagenes: ["https://iili.io/fubavf4.webp"],
      },
      {
        placa: "EFG-789",
        marca: "Hyundai",
        modelo: "Accent",
        anio: 2020,
        kilometraje: 48000,
        fechaVencimientoSoat: getDateString(100),
        estado: "activo",
        imagenes: ["https://iili.io/fuba80l.webp"],
      },
      {
        placa: "HIJ-012",
        marca: "Nissan",
        modelo: "Versa",
        anio: 2021,
        kilometraje: 32000,
        fechaVencimientoSoat: getDateString(140),
        estado: "activo",
        imagenes: ["https://iili.io/fubaSg2.webp"],
      },
      {
        placa: "KLM-345",
        marca: "Honda",
        modelo: "City",
        anio: 2019,
        kilometraje: 75000,
        fechaVencimientoSoat: getDateString(45),
        estado: "activo",
        imagenes: ["https://iili.io/fubar57.webp"],
      },
      {
        placa: "NOP-678",
        marca: "Mazda",
        modelo: "2",
        anio: 2020,
        kilometraje: 52000,
        fechaVencimientoSoat: getDateString(110),
        estado: "activo",
        imagenes: ["https://iili.io/fuba4e9.webp"],
      },
      {
        placa: "QRS-901",
        marca: "Chevrolet",
        modelo: "Sail",
        anio: 2018,
        kilometraje: 88000,
        fechaVencimientoSoat: getDateString(-20),
        estado: "taller",
        imagenes: ["https://iili.io/fubaizu.webp"],
      },
      {
        placa: "TUV-234",
        marca: "Kia",
        modelo: "Rio",
        anio: 2021,
        kilometraje: 38000,
        fechaVencimientoSoat: getDateString(190),
        estado: "activo",
        imagenes: ["https://iili.io/fubasWb.webp"],
      },
      {
        placa: "WXY-567",
        marca: "Volkswagen",
        modelo: "Polo",
        anio: 2022,
        kilometraje: 18000,
        fechaVencimientoSoat: getDateString(280),
        estado: "activo",
        imagenes: ["https://iili.io/fubaZqx.webp"],
      },
      {
        placa: "ZAB-890",
        marca: "Ford",
        modelo: "Fiesta",
        anio: 2019,
        kilometraje: 68000,
        fechaVencimientoSoat: getDateString(75),
        estado: "activo",
        imagenes: ["https://iili.io/fubaDgV.webp"],
      },
      {
        placa: "CDE-123",
        marca: "Suzuki",
        modelo: "Swift",
        anio: 2020,
        kilometraje: 42000,
        fechaVencimientoSoat: getDateString(130),
        estado: "activo",
        imagenes: ["https://iili.io/fubamdB.webp"],
      },
      {
        placa: "FGH-456",
        marca: "Toyota",
        modelo: "Camry",
        anio: 2021,
        kilometraje: 25000,
        fechaVencimientoSoat: getDateString(220),
        estado: "activo",
        imagenes: ["https://iili.io/fubaye1.webp"],
      },
      {
        placa: "IJK-789",
        marca: "Hyundai",
        modelo: "Sonata",
        anio: 2020,
        kilometraje: 58000,
        fechaVencimientoSoat: getDateString(85),
        estado: "activo",
        imagenes: ["https://iili.io/fubc9mF.webp"],
      },
      {
        placa: "LMN-012",
        marca: "Nissan",
        modelo: "Altima",
        anio: 2019,
        kilometraje: 72000,
        fechaVencimientoSoat: getDateString(50),
        estado: "activo",
        imagenes: ["https://iili.io/fubcdXa.webp"],
      },
      {
        placa: "OPQ-345",
        marca: "Honda",
        modelo: "Accord",
        anio: 2022,
        kilometraje: 12000,
        fechaVencimientoSoat: getDateString(300),
        estado: "activo",
        imagenes: ["https://iili.io/fubc2LJ.webp"],
      },
      {
        placa: "RST-678",
        marca: "Mazda",
        modelo: "6",
        anio: 2021,
        kilometraje: 36000,
        fechaVencimientoSoat: getDateString(160),
        estado: "activo",
        imagenes: ["https://iili.io/fubcBdN.webp"],
      },
      {
        placa: "UVW-901",
        marca: "Chevrolet",
        modelo: "Malibu",
        anio: 2020,
        kilometraje: 62000,
        fechaVencimientoSoat: getDateString(95),
        estado: "activo",
        imagenes: ["https://iili.io/fubcnet.webp"],
      },
      {
        placa: "XYZ-234",
        marca: "Kia",
        modelo: "Optima",
        anio: 2019,
        kilometraje: 78000,
        fechaVencimientoSoat: getDateString(-10),
        estado: "taller",
        imagenes: ["https://iili.io/fubczIn.webp"],
      },
      {
        placa: "ABC-567",
        marca: "Volkswagen",
        modelo: "Passat",
        anio: 2021,
        kilometraje: 40000,
        fechaVencimientoSoat: getDateString(180),
        estado: "activo",
        imagenes: ["https://iili.io/fubcTLG.webp"],
      },
      {
        placa: "DEF-890",
        marca: "Ford",
        modelo: "Fusion",
        anio: 2020,
        kilometraje: 54000,
        fechaVencimientoSoat: getDateString(115),
        estado: "activo",
        imagenes: ["https://iili.io/fubc5rl.webp"],
      },
      {
        placa: "GHI-123",
        marca: "Suzuki",
        modelo: "Baleno",
        anio: 2022,
        kilometraje: 22000,
        fechaVencimientoSoat: getDateString(260),
        estado: "activo",
        imagenes: ["https://iili.io/fubcY22.webp"],
      },
    ])
    .returning();

  console.log("✅ Vehicles inserted");
  return vehiclesData;
}
