import { database } from "@db/connection.db";
import { viajes } from "@model/tables/viaje.model";
import { Ruta } from "@model/tables/ruta.model";
import { Cliente } from "@model/tables/cliente.model";
import { getDateTime } from "@function/date.function";

export async function seedViajes(clientesData: Cliente[], routesData: Ruta[]) {
  console.log("🌱 Seeding trips...");

  if (clientesData.length === 0 || routesData.length === 0) {
    console.log("⚠️ Skipping trips (missing dependencies)");
    return;
  }

  await database.insert(viajes).values([
    {
      rutaId: routesData[0].id,
      tipoRuta: "fija",
      clienteId: clientesData[0].id,
      tripulantes: ["Carlos Mendoza", "Ana Torres"],
      modalidadServicio: "regular",
      fechaSalida: getDateTime(-30, 8),
      fechaLlegada: getDateTime(-30, 12),
      estado: "completado",
    },
    {
      rutaId: routesData[1].id,
      tipoRuta: "fija",
      clienteId: clientesData[1].id,
      tripulantes: ["Luis Ramírez"],
      modalidadServicio: "expreso",
      fechaSalida: getDateTime(-28, 9),
      fechaLlegada: getDateTime(-28, 14, 30),
      estado: "completado",
    },
    {
      rutaOcasional: "Lima - Playa de Máncora (Viaje especial)",
      tipoRuta: "ocasional",
      clienteId: clientesData[2].id,
      tripulantes: ["Jorge Flores", "Patricia Díaz", "Miguel Soto"],
      modalidadServicio: "turismo",
      fechaSalida: getDateTime(-26, 7),
      fechaLlegada: getDateTime(-26, 13),
      estado: "completado",
    },
    {
      rutaId: routesData[3].id,
      tipoRuta: "fija",
      clienteId: clientesData[3].id,
      tripulantes: ["Roberto Salas"],
      modalidadServicio: "ejecutivo",
      fechaSalida: getDateTime(-24, 8, 30),
      fechaLlegada: getDateTime(-24, 16),
      estado: "completado",
    },
    {
      rutaId: routesData[4].id,
      tipoRuta: "fija",
      clienteId: clientesData[4].id,
      tripulantes: ["Sandra Vega", "Pedro Cruz"],
      modalidadServicio: "regular",
      fechaSalida: getDateTime(-22, 10),
      fechaLlegada: getDateTime(-22, 18),
      estado: "completado",
    },
    {
      rutaOcasional: "Cusco - Valle Sagrado (Tour privado)",
      tipoRuta: "ocasional",
      clienteId: clientesData[5].id,
      tripulantes: ["Fernando Rojas", "Lucia Paredes"],
      modalidadServicio: "especial",
      fechaSalida: getDateTime(-20, 6),
      fechaLlegada: getDateTime(-20, 14),
      estado: "completado",
    },
    {
      rutaId: routesData[6].id,
      tipoRuta: "fija",
      clienteId: clientesData[6].id,
      tripulantes: ["Andrés Morales"],
      modalidadServicio: "expreso",
      fechaSalida: getDateTime(-18, 9),
      fechaLlegada: getDateTime(-18, 13),
      estado: "completado",
    },
    {
      rutaId: routesData[7].id,
      tipoRuta: "fija",
      clienteId: clientesData[7].id,
      tripulantes: ["Carla Gutiérrez"],
      modalidadServicio: "regular",
      fechaSalida: getDateTime(-16, 7, 30),
      fechaLlegada: getDateTime(-16, 12, 30),
      estado: "completado",
    },
    {
      rutaOcasional: "Arequipa - Cañón del Colca (Excursión)",
      tipoRuta: "ocasional",
      clienteId: clientesData[8].id,
      tripulantes: ["Diego Vargas", "Elena Castillo"],
      modalidadServicio: "turismo",
      fechaSalida: getDateTime(-14, 8),
      fechaLlegada: getDateTime(-14, 14),
      estado: "completado",
    },
    {
      rutaId: routesData[9].id,
      tipoRuta: "fija",
      clienteId: clientesData[9].id,
      tripulantes: ["Raúl Jiménez"],
      modalidadServicio: "ejecutivo",
      fechaSalida: getDateTime(-12, 10),
      fechaLlegada: getDateTime(-12, 14, 30),
      estado: "completado",
    },
    {
      rutaId: routesData[10].id,
      tipoRuta: "fija",
      clienteId: clientesData[10].id,
      tripulantes: ["Beatriz Núñez", "Francisco Reyes"],
      modalidadServicio: "regular",
      fechaSalida: getDateTime(-10, 6, 30),
      fechaLlegada: getDateTime(-10, 11),
      estado: "completado",
    },
    {
      rutaOcasional: "Ica - Paracas (Servicio privado)",
      tipoRuta: "ocasional",
      clienteId: clientesData[11].id,
      tripulantes: ["Gabriel Herrera", "Mariana López", "Sebastián Ortiz"],
      modalidadServicio: "especial",
      fechaSalida: getDateTime(-8, 9),
      fechaLlegada: getDateTime(-8, 17),
      estado: "completado",
    },
    {
      rutaId: routesData[12].id,
      tipoRuta: "fija",
      clienteId: clientesData[12].id,
      tripulantes: ["Natalia Romero"],
      modalidadServicio: "expreso",
      fechaSalida: getDateTime(-6, 8),
      fechaLlegada: getDateTime(-6, 18),
      estado: "completado",
    },
    {
      rutaId: routesData[13].id,
      tipoRuta: "fija",
      clienteId: clientesData[13].id,
      tripulantes: ["Víctor Peña", "Isabel Medina"],
      modalidadServicio: "ejecutivo",
      fechaSalida: getDateTime(-5, 7),
      fechaLlegada: getDateTime(-5, 19),
      estado: "completado",
    },
    {
      rutaId: routesData[14].id,
      tipoRuta: "fija",
      clienteId: clientesData[14].id,
      tripulantes: ["Tomás Ríos"],
      modalidadServicio: "regular",
      fechaSalida: getDateTime(-4, 10),
      fechaLlegada: getDateTime(-4, 12),
      estado: "completado",
    },
    {
      rutaOcasional: "Trujillo - Huanchaco (Tour playero)",
      tipoRuta: "ocasional",
      clienteId: clientesData[15].id,
      tripulantes: ["Mónica Silva", "Javier Campos"],
      modalidadServicio: "turismo",
      fechaSalida: getDateTime(-3, 8, 30),
      fechaLlegada: getDateTime(-3, 11),
      estado: "completado",
    },
    {
      rutaId: routesData[16].id,
      tipoRuta: "fija",
      clienteId: clientesData[16].id,
      tripulantes: ["Alejandro Chávez"],
      modalidadServicio: "expreso",
      fechaSalida: getDateTime(-2, 9),
      fechaLlegada: getDateTime(-2, 12),
      estado: "completado",
    },
    {
      rutaId: routesData[17].id,
      tipoRuta: "fija",
      clienteId: clientesData[17].id,
      tripulantes: ["Verónica Fuentes", "Ernesto Aguilar", "Daniela Córdoba"],
      modalidadServicio: "regular",
      fechaSalida: getDateTime(-1, 7),
      fechaLlegada: getDateTime(-1, 11, 30),
      estado: "completado",
    },
    {
      rutaId: routesData[18].id,
      tipoRuta: "fija",
      clienteId: clientesData[18].id,
      tripulantes: ["Hugo Zamora"],
      modalidadServicio: "ejecutivo",
      fechaSalida: getDateTime(0, 8),
      estado: "en_progreso",
    },
    {
      rutaOcasional: "Lima - Lunahuaná (Aventura)",
      tipoRuta: "ocasional",
      clienteId: clientesData[19].id,
      tripulantes: ["Claudia Bravo", "Manuel Escobar"],
      modalidadServicio: "especial",
      fechaSalida: getDateTime(0, 10),
      estado: "en_progreso",
    },
    {
      rutaId: routesData[20].id,
      tipoRuta: "fija",
      clienteId: clientesData[20].id,
      tripulantes: ["Ricardo Delgado"],
      modalidadServicio: "regular",
      fechaSalida: getDateTime(1, 8, 30),
      estado: "programado",
    },
    {
      rutaId: routesData[21].id,
      tipoRuta: "fija",
      clienteId: clientesData[21].id,
      tripulantes: ["Paola Méndez", "Alberto Santos"],
      modalidadServicio: "expreso",
      fechaSalida: getDateTime(2, 10),
      estado: "programado",
    },
    {
      rutaId: routesData[22].id,
      tipoRuta: "fija",
      clienteId: clientesData[22].id,
      tripulantes: ["Gabriela Navarro"],
      modalidadServicio: "regular",
      fechaSalida: getDateTime(3, 9),
      estado: "programado",
    },
    {
      rutaOcasional: "Puno - Islas Flotantes (Tour lacustre)",
      tipoRuta: "ocasional",
      clienteId: clientesData[23].id,
      tripulantes: ["Óscar Ibarra", "Lorena Valdez", "Mario Ponce"],
      modalidadServicio: "turismo",
      fechaSalida: getDateTime(4, 7, 30),
      estado: "programado",
    },
    {
      rutaId: routesData[24].id,
      tipoRuta: "fija",
      clienteId: clientesData[24].id,
      tripulantes: ["Sofía Ramos", "Marcos Luna"],
      modalidadServicio: "ejecutivo",
      fechaSalida: getDateTime(5, 8),
      estado: "programado",
    },
    {
      rutaId: routesData[25].id,
      tipoRuta: "fija",
      clienteId: clientesData[25].id,
      tripulantes: ["Eduardo Prieto"],
      modalidadServicio: "regular",
      fechaSalida: getDateTime(6, 9, 30),
      estado: "programado",
    },
    {
      rutaId: routesData[26].id,
      tipoRuta: "fija",
      clienteId: clientesData[26].id,
      tripulantes: ["Carolina Bustos", "Ignacio Araya"],
      modalidadServicio: "expreso",
      fechaSalida: getDateTime(7, 10),
      estado: "programado",
    },
    {
      rutaOcasional: "Nazca - Sobrevuelo Líneas de Nazca",
      tipoRuta: "ocasional",
      clienteId: clientesData[27].id,
      tripulantes: ["Adriana Guerrero"],
      modalidadServicio: "especial",
      fechaSalida: getDateTime(8, 8),
      estado: "programado",
    },
    {
      rutaId: routesData[28].id,
      tipoRuta: "fija",
      clienteId: clientesData[28].id,
      tripulantes: ["Felipe Cortés", "Valeria Ruiz", "Cristian Márquez"],
      modalidadServicio: "regular",
      fechaSalida: getDateTime(9, 7),
      estado: "programado",
    },
    {
      rutaId: routesData[29].id,
      tipoRuta: "fija",
      clienteId: clientesData[29].id,
      tripulantes: ["Rodrigo León", "Teresa Salazar"],
      modalidadServicio: "ejecutivo",
      fechaSalida: getDateTime(10, 9),
      estado: "programado",
    },
  ]);

  console.log("✅ Trips inserted");
}
