import { VehiculoChecklistDocumentItemCreateDto } from '../create-checklist-document.dto';
import { CinturonesSeguridadDto } from '../types/cinturones-seguridad.dto';
import { defineItem } from '../checklist.helper';

const items = [
  defineItem('Asiento Piloto', 1, { camposExtras: ['observacion'] }),
  defineItem('Asiento Copiloto', 2, { camposExtras: ['observacion'] }),
  defineItem('Asiento 1', 3, { camposExtras: ['observacion'] }),
  defineItem('Asiento 2', 4, { camposExtras: ['observacion'] }),
  defineItem('Asiento 3', 5, { camposExtras: ['observacion'] }),
  defineItem('Asiento 4', 6, { camposExtras: ['observacion'] }),
  defineItem('Asiento 5', 7, { camposExtras: ['observacion'] }),
  defineItem('Asiento 6', 8, { camposExtras: ['observacion'] }),
  defineItem('Asiento 7', 9, { camposExtras: ['observacion'] }),
  defineItem('Asiento 8', 10, { camposExtras: ['observacion'] }),
  defineItem('Asiento 9', 11, { camposExtras: ['observacion'] }),
  defineItem('Asiento 10', 12, { camposExtras: ['observacion'] }),
  defineItem('Asiento 11', 13, { camposExtras: ['observacion'] }),
  defineItem('Asiento 12', 14, { camposExtras: ['observacion'] }),
  defineItem('Asiento 13', 15, { camposExtras: ['observacion'] }),
  defineItem('Asiento 14', 16, { camposExtras: ['observacion'] }),
  defineItem('Asiento 15', 17, { camposExtras: ['observacion'] }),
  defineItem('Asiento 16', 18, { camposExtras: ['observacion'] }),
  defineItem('Asiento 17', 19, { camposExtras: ['observacion'] }),
  defineItem('Asiento 18', 20, { camposExtras: ['observacion'] }),
  defineItem('Asiento 19', 21, { camposExtras: ['observacion'] }),
  defineItem('Asiento 20', 22, { camposExtras: ['observacion'] }),
  defineItem('Asiento 21', 23, { camposExtras: ['observacion'] }),
  defineItem('Asiento 22', 24, { camposExtras: ['observacion'] }),
  defineItem('Asiento 23', 25, { camposExtras: ['observacion'] }),
  defineItem('Asiento 24', 26, { camposExtras: ['observacion'] }),
  defineItem('Asiento 25', 27, { camposExtras: ['observacion'] }),
  defineItem('Asiento 26', 28, { camposExtras: ['observacion'] }),
  defineItem('Asiento 27', 29, { camposExtras: ['observacion'] }),
  defineItem('Asiento 28', 30, { camposExtras: ['observacion'] }),
  defineItem('Asiento 29', 31, { camposExtras: ['observacion'] }),
  defineItem('Asiento 30', 32, { camposExtras: ['observacion'] }),
  defineItem('Asiento 31', 33, { camposExtras: ['observacion'] }),
  defineItem('Asiento 32', 34, { camposExtras: ['observacion'] }),
  defineItem('Asiento 33', 35, { camposExtras: ['observacion'] }),
  defineItem('Asiento 34', 36, { camposExtras: ['observacion'] }),
  defineItem('Asiento 35', 37, { camposExtras: ['observacion'] }),
  defineItem('Asiento 36', 38, { camposExtras: ['observacion'] }),
  defineItem('Asiento 37', 39, { camposExtras: ['observacion'] }),
  defineItem('Asiento 38', 40, { camposExtras: ['observacion'] }),
  defineItem('Asiento 39', 41, { camposExtras: ['observacion'] }),
  defineItem('Asiento 40', 42, { camposExtras: ['observacion'] }),
  defineItem('Asiento 41', 43, { camposExtras: ['observacion'] }),
  defineItem('Asiento 42', 44, { camposExtras: ['observacion'] }),
  defineItem('Asiento 43', 45, { camposExtras: ['observacion'] }),
  defineItem('Asiento 44', 46, { camposExtras: ['observacion'] }),
  defineItem('Asiento 45', 47, { camposExtras: ['observacion'] }),
  defineItem('Asiento 46', 48, { camposExtras: ['observacion'] }),
  defineItem('Asiento 47', 49, { camposExtras: ['observacion'] }),
  defineItem('Asiento 48', 50, { camposExtras: ['observacion'] }),
  defineItem('Asiento 49', 51, { camposExtras: ['observacion'] }),
  defineItem('Asiento 50', 52, { camposExtras: ['observacion'] }),
  defineItem('Asiento 51', 53, { camposExtras: ['observacion'] }),
  defineItem('Asiento 52', 54, { camposExtras: ['observacion'] }),
];

export type CinturonesSeguridadLabel = (typeof items)[number]['label'];

export const CinturonesSeguridadModel: VehiculoChecklistDocumentItemCreateDto[] = items;

export const CinturonesSeguridadMap: Record<CinturonesSeguridadLabel, keyof CinturonesSeguridadDto> = {
  'Asiento Piloto': 'asientoPiloto',
  'Asiento Copiloto': 'asientoCopiloto',
  'Asiento 1': 'asiento1',
  'Asiento 2': 'asiento2',
  'Asiento 3': 'asiento3',
  'Asiento 4': 'asiento4',
  'Asiento 5': 'asiento5',
  'Asiento 6': 'asiento6',
  'Asiento 7': 'asiento7',
  'Asiento 8': 'asiento8',
  'Asiento 9': 'asiento9',
  'Asiento 10': 'asiento10',
  'Asiento 11': 'asiento11',
  'Asiento 12': 'asiento12',
  'Asiento 13': 'asiento13',
  'Asiento 14': 'asiento14',
  'Asiento 15': 'asiento15',
  'Asiento 16': 'asiento16',
  'Asiento 17': 'asiento17',
  'Asiento 18': 'asiento18',
  'Asiento 19': 'asiento19',
  'Asiento 20': 'asiento20',
  'Asiento 21': 'asiento21',
  'Asiento 22': 'asiento22',
  'Asiento 23': 'asiento23',
  'Asiento 24': 'asiento24',
  'Asiento 25': 'asiento25',
  'Asiento 26': 'asiento26',
  'Asiento 27': 'asiento27',
  'Asiento 28': 'asiento28',
  'Asiento 29': 'asiento29',
  'Asiento 30': 'asiento30',
  'Asiento 31': 'asiento31',
  'Asiento 32': 'asiento32',
  'Asiento 33': 'asiento33',
  'Asiento 34': 'asiento34',
  'Asiento 35': 'asiento35',
  'Asiento 36': 'asiento36',
  'Asiento 37': 'asiento37',
  'Asiento 38': 'asiento38',
  'Asiento 39': 'asiento39',
  'Asiento 40': 'asiento40',
  'Asiento 41': 'asiento41',
  'Asiento 42': 'asiento42',
  'Asiento 43': 'asiento43',
  'Asiento 44': 'asiento44',
  'Asiento 45': 'asiento45',
  'Asiento 46': 'asiento46',
  'Asiento 47': 'asiento47',
  'Asiento 48': 'asiento48',
  'Asiento 49': 'asiento49',
  'Asiento 50': 'asiento50',
  'Asiento 51': 'asiento51',
  'Asiento 52': 'asiento52',
};
